FOR LOOP

In [1]:
name = 'nit'
for i in name:
    print(i)

n
i
t


In [2]:
name1 = [1,3.5,'hallo'] #i want print the value individualy

for i in name1:
    print(i)

1
3.5
hallo


In [3]:
for i in [2, 3, 7.8, 'hi']:
    print(i)

2
3
7.8
hi


In [4]:
range(5)

range(0, 5)

In [6]:
for i in range(2,5):
    print(i)

2
3
4


In [7]:
for i in range(1,10,3):
    print(i)

1
4
7


In [8]:
for i in range(1,21):
    print(i)   



1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20


In [1]:
for i in range(1,51):
    if i%5==0:
        print(i)

5
10
15
20
25
30
35
40
45
50


In [5]:
for i in range(5):
    print(i)

0
1
2
3
4


In [2]:
for i in range(1,51):
    if i%5!=0:
        print(i)

1
2
3
4
6
7
8
9
11
12
13
14
16
17
18
19
21
22
23
24
26
27
28
29
31
32
33
34
36
37
38
39
41
42
43
44
46
47
48
49


In [10]:
# LETS DISCUSS ABOUT 3 KEYWORDS -- BREAK || CONTINUE || PASS
#BREAK STATEMNT - if you apply break statment in a loop then it will end the loop
# Pass = skips block of code( function, class etc)
# Continue= skips 1 step/iteration during loop 
# Break= jumps out of the function/loop

BREAK STATEMENT

In [11]:
# write the code user ask chocklet from vendor machne write the basic code 

x = int(input('How many choclets you want:?'))

i = 1
while i<=x:
    print('choclet')
    i += 1       

How many choclets you want:? 12


choclet
choclet
choclet
choclet
choclet
choclet
choclet
choclet
choclet
choclet
choclet
choclet


In [12]:
ava = 5 # the machine has only 5 choclet 

x = int(input('How many choclets you want:?'))

i = 1
while i<=x:
    print('choclet')
    i += 1   
# if you check the user wants 10 choclets  but availabe choclet is 5 but we got output as 10 choclet
# in this code we just declare but we dint apply any condition to it 

How many choclets you want:? 13


choclet
choclet
choclet
choclet
choclet
choclet
choclet
choclet
choclet
choclet
choclet
choclet
choclet


In [13]:
available_choclet = 5 # the machine has only 10 candis 

x = int(input('How many choclets user want:?'))

i = 1
while i<=x:
    
    if i>available_choclet: # we stop the execution but which code execution not entire code , i want to come out of while loop 
        break # break is statement | means jump out of the loop
    print('choclet')
    i += 1   
    
print('bye for now')

How many choclets user want:? 59


choclet
choclet
choclet
choclet
choclet
bye for now


In [15]:
available_choclet = 5 # the machine has only 10 candis 

x = int(input('How many choclets you want:?'))

i = 1
while i<=x:
    
    if i>available_choclet: # we stop the execution but which code execution not entire code , i want to come out of while loop 
        print('out of stock')
        break # break is statement | means jump out of the loop
    print('choclet')
    i += 1   
    
print('bye for now')

How many choclets you want:? 5


choclet
choclet
choclet
choclet
choclet
bye for now


In [4]:
for i in range (1,11):
    print(i)

1
2
3
4
5
6
7
8
9
10


In [5]:
for i in range (1,11):
    if i == 5:
        break
    print(i)

1
2
3
4


In [7]:
for i in range (1,11):
    if i == 10:
        break
    print(i)

1
2
3
4
5
6
7
8
9


In [8]:
for i in range (1,11):
    if i == 5:
        continue
    print(i)

1
2
3
4
6
7
8
9
10


In [9]:
for i in range (1,11):
    if i == 5:
        break
    print('hello :',i)

hello : 1
hello : 2
hello : 3
hello : 4


In [10]:
for i in range (1,11):
    if i == 5:
        continue
    print('hello :',i)

hello : 1
hello : 2
hello : 3
hello : 4
hello : 6
hello : 7
hello : 8
hello : 9
hello : 10


In [11]:
for i in range (1,11):

_IncompleteInputError: incomplete input (62142296.py, line 1)

In [12]:
for i in range (1,11):
    pass

In [15]:
#print no which is range 1 to 50, which is divisinle by 3 or 5
for i in range (1,51):
    if i%3 == 0:
       print(i)  
print( end)
    

3
6
9
12
15
18
21
24
27
30
33
36
39
42
45
48


NameError: name 'end' is not defined

In [16]:
for i in range (1,51):
    if i%3 == 0:
        continue
    print(i)  
print( 'end')
    

1
2
4
5
7
8
10
11
13
14
16
17
19
20
22
23
25
26
28
29
31
32
34
35
37
38
40
41
43
44
46
47
49
50
end


In [17]:
for i in range (1,51):
    if i%3 == 0 or i % 5 == 0:
        continue
    print(i)  
print( 'end')
    

1
2
4
7
8
11
13
14
16
17
19
22
23
26
28
29
31
32
34
37
38
41
43
44
46
47
49
end


PRINTING PATTERN

In [20]:
# this is pattern
####
####
####
####

print('####')
print('####')
print('####')
print('####')

####
####
####
####


In [22]:
for i in range (1,5):
    i = i + 1
    print('####')

####
####
####
####


In [23]:
for i in range (1,5):
    i = i<=5
    print('####')

####
####
####
####


In [24]:
for i in range (4):
    for j in range (i + 1):
        print('#', end = "")
    print()

#
##
###
####


In [26]:
for i in range (4):
    for j in range (4 - i):
        print('#', end = "")
    print()

####
###
##
#


FOR-ELSE

In [27]:
nums = [12,15,18,21,26,20,30]
for num in nums:
    if num % 5 == 0:
        print(num)

15
20
30


In [28]:
nums = [12,15,18,21,26,20,30]
for num in nums:
    if num % 5 == 0:
        print(num)
        break

15


In [29]:
nums = [12,67,18,21,26,20,30]
for num in nums:
    if num % 5 == 0:
        print(num)

20
30


In [31]:
nums = [12,18,21,26]
for num in nums:
    if num % 5 == 0:
        print(num)
        break
    else:
        print("no not found")

no not found
no not found
no not found
no not found


In [32]:
nums = [12,18,21,26]
for num in nums:
    if num % 5 == 0:
        print(num)
        break
else:
        print("no not found")

no not found


In [33]:
nums = 13
for i in range (2,num):
    if num % i == 0:
        print('not prime number')
        break
    else:
        print("prime number")

not prime number


In [16]:
from array import * 
arr = array('i',[])

n = int(input('Enter the length of the array'))

for i in range(5):
    x = int(input('Enter the next value'))
    arr.append(x)
print(arr)

Enter the length of the array 6
Enter the next value 6
Enter the next value 8
Enter the next value 9
Enter the next value 5
Enter the next value 9


array('i', [6, 8, 9, 5, 9])


In [23]:
from array import * 
arr = array('i',[])

n = int(input('Enter the length of the array'))

for i in range(5):
    x = int(input('Enter the next value'))
    arr.append(x)
print(arr)

Enter the length of the array 7
Enter the next value 4
Enter the next value 6
Enter the next value 99
Enter the next value 0
Enter the next value 6


array('i', [4, 6, 99, 0, 6])


In [18]:
from array import * 
arr = array('i',[])

n = input('Enter the length of the array')

for i in range(5):
    x = input('Enter the next value')
    arr.append(x)
print(arr)

Enter the length of the array 4
Enter the next value 5


TypeError: 'str' object cannot be interpreted as an integer

NUMPY

In [35]:
import numpy as np

In [36]:
np.__version__

'2.1.3'

In [ ]:
import sys


In [38]:
# creat list
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [39]:
type(my_list)

list

In [41]:
# how to convert list to array
arr = np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [42]:
type(arr)

numpy.ndarray

In [43]:
print(type(my_list))
print(type(arr))

<class 'list'>
<class 'numpy.ndarray'>


In [44]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [45]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [46]:
np.arange(5,100,10)

array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

In [48]:
np.arange(20,10)# 1st argument is always less than 2nd argument

array([], dtype=int64)

In [49]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [19]:
from numpy import *
arr = array([1,2,3,4,5])
print(arr)
type(arr)

[1 2 3 4 5]


numpy.ndarray

In [21]:
type(arr.dtype)


numpy.dtypes.Int64DType

In [22]:
arr = array([1,2,3,4,5.9])
print(arr)

[1.  2.  3.  4.  5.9]
