In [3]:
import numpy as np

In [4]:
# creat list
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [5]:
type(my_list)

list

In [6]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [7]:
np.arange(5,100,10)

array([ 5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

In [8]:
np.zeros(5)#paramiter tunning

array([0., 0., 0., 0., 0.])

In [9]:
np.zeros(5,dtype = int)# Hyper paramiter tunning

array([0, 0, 0, 0, 0])

In [10]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [11]:
np.zeros((2,3),dtype = int)

array([[0, 0, 0],
       [0, 0, 0]])

In [12]:
np.zeros((10,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [13]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [14]:
np.ones((2,3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [15]:
np.two((2,3), dtype=int)

AttributeError: module 'numpy' has no attribute 'two'

In [16]:
np.three(4)

AttributeError: module 'numpy' has no attribute 'three'

In [17]:
rand(2,3)

NameError: name 'rand' is not defined

In [18]:
random.rand(2,3)

NameError: name 'random' is not defined

In [19]:
np.random.rand(2)# it will generate only floate value

array([0.31290164, 0.90809552])

In [20]:
np.random.rand(2,3)

array([[0.87511163, 0.16944832, 0.2166054 ],
       [0.03265898, 0.59260878, 0.48528568]])

In [21]:
np.random.randint(2)# it always 2 value 1, and 0

1

In [22]:
np.random.randint(2,9)

5

In [24]:
#generate random integer between 2 - 9 where 9 is exclude, 
np.random.randint(2,9,4)# give me 4 random integer

array([8, 8, 3, 8], dtype=int32)

In [32]:
np.random.randint(10,40,(10,10))

array([[20, 11, 27, 35, 34, 33, 24, 28, 24, 35],
       [30, 32, 36, 16, 27, 18, 39, 13, 38, 21],
       [31, 34, 28, 10, 13, 16, 31, 30, 33, 25],
       [35, 11, 10, 17, 17, 35, 35, 11, 38, 10],
       [16, 35, 39, 10, 32, 12, 28, 15, 31, 33],
       [28, 32, 15, 10, 22, 24, 28, 27, 31, 17],
       [10, 32, 17, 29, 18, 36, 33, 26, 16, 28],
       [10, 21, 27, 23, 36, 12, 30, 29, 17, 38],
       [23, 19, 38, 39, 30, 38, 21, 34, 37, 31],
       [39, 37, 27, 17, 39, 24, 36, 23, 22, 33]], dtype=int32)

In [88]:
np.random.rand(5)

array([0.94590013, 0.53087039, 0.96652952, 0.80792056, 0.71491189])

In [89]:
np.rand(4)

AttributeError: module 'numpy' has no attribute 'rand'

In [90]:
np.random.rand(3,5)

array([[0.98711812, 0.98153185, 0.55883843, 0.75430657, 0.81867038],
       [0.27679513, 0.48051809, 0.90755378, 0.53774302, 0.4307435 ],
       [0.31380287, 0.80100248, 0.59034044, 0.91770491, 0.30220346]])

In [91]:
np.random.randint(4,6)

5

In [92]:
np.random.randint(2,20,4)

array([ 5,  6, 15, 10], dtype=int32)

In [93]:
np.random.randint(0,1) 

0

In [94]:
np.random.randint(10,20,5)

array([15, 17, 17, 16, 15], dtype=int32)

In [95]:
np.arange(1,13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [96]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [97]:
np.arange(1,13).reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [98]:
np.arange(1,13).reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [26]:
import numpy as np

def generate_otp(length=4):
    # Generate OTP of given length using np.random.randint
    otp = ''.join([str(np.random.randint(0, 10)) for _ in range(length)])
    return otp

# Example usage
print("Your OTP is:", generate_otp())

Your OTP is: 8099


In [28]:
arr1 = np.random.randint(10,40,(10,10))
print(arr1)

[[12 29 28 22 19 14 29 37 19 19]
 [29 14 23 23 20 27 23 31 36 36]
 [16 10 25 36 27 32 38 19 18 12]
 [38 22 20 31 25 16 36 24 10 12]
 [14 21 36 33 27 20 22 26 22 28]
 [22 29 27 24 31 22 19 20 16 22]
 [10 30 29 19 27 25 34 24 15 38]
 [12 25 20 26 27 32 13 38 11 29]
 [20 13 34 21 26 34 29 14 11 29]
 [18 23 22 25 36 19 28 25 32 28]]


In [29]:
arr1

array([[12, 29, 28, 22, 19, 14, 29, 37, 19, 19],
       [29, 14, 23, 23, 20, 27, 23, 31, 36, 36],
       [16, 10, 25, 36, 27, 32, 38, 19, 18, 12],
       [38, 22, 20, 31, 25, 16, 36, 24, 10, 12],
       [14, 21, 36, 33, 27, 20, 22, 26, 22, 28],
       [22, 29, 27, 24, 31, 22, 19, 20, 16, 22],
       [10, 30, 29, 19, 27, 25, 34, 24, 15, 38],
       [12, 25, 20, 26, 27, 32, 13, 38, 11, 29],
       [20, 13, 34, 21, 26, 34, 29, 14, 11, 29],
       [18, 23, 22, 25, 36, 19, 28, 25, 32, 28]], dtype=int32)

In [30]:
print(arr1)

[[12 29 28 22 19 14 29 37 19 19]
 [29 14 23 23 20 27 23 31 36 36]
 [16 10 25 36 27 32 38 19 18 12]
 [38 22 20 31 25 16 36 24 10 12]
 [14 21 36 33 27 20 22 26 22 28]
 [22 29 27 24 31 22 19 20 16 22]
 [10 30 29 19 27 25 34 24 15 38]
 [12 25 20 26 27 32 13 38 11 29]
 [20 13 34 21 26 34 29 14 11 29]
 [18 23 22 25 36 19 28 25 32 28]]


In [31]:
arr1[5]

array([22, 29, 27, 24, 31, 22, 19, 20, 16, 22], dtype=int32)

In [32]:
arr2 = np.random.randint(2, 9,(5,7)) 
print(arr2)

[[6 6 6 5 5 2 5]
 [5 8 2 3 2 7 8]
 [4 4 2 7 7 3 5]
 [2 6 5 5 7 5 4]
 [8 6 4 6 3 2 3]]


In [33]:
arr2[-4] 

array([5, 8, 2, 3, 2, 7, 8], dtype=int32)

In [34]:
arr2

array([[6, 6, 6, 5, 5, 2, 5],
       [5, 8, 2, 3, 2, 7, 8],
       [4, 4, 2, 7, 7, 3, 5],
       [2, 6, 5, 5, 7, 5, 4],
       [8, 6, 4, 6, 3, 2, 3]], dtype=int32)

In [35]:
arr2[2:10] 

array([[4, 4, 2, 7, 7, 3, 5],
       [2, 6, 5, 5, 7, 5, 4],
       [8, 6, 4, 6, 3, 2, 3]], dtype=int32)

In [36]:
arr2

array([[6, 6, 6, 5, 5, 2, 5],
       [5, 8, 2, 3, 2, 7, 8],
       [4, 4, 2, 7, 7, 3, 5],
       [2, 6, 5, 5, 7, 5, 4],
       [8, 6, 4, 6, 3, 2, 3]], dtype=int32)

In [37]:
arr2[:]

array([[6, 6, 6, 5, 5, 2, 5],
       [5, 8, 2, 3, 2, 7, 8],
       [4, 4, 2, 7, 7, 3, 5],
       [2, 6, 5, 5, 7, 5, 4],
       [8, 6, 4, 6, 3, 2, 3]], dtype=int32)

In [38]:
arr2[::-1]

array([[8, 6, 4, 6, 3, 2, 3],
       [2, 6, 5, 5, 7, 5, 4],
       [4, 4, 2, 7, 7, 3, 5],
       [5, 8, 2, 3, 2, 7, 8],
       [6, 6, 6, 5, 5, 2, 5]], dtype=int32)

In [40]:
arr2

array([[6, 6, 6, 5, 5, 2, 5],
       [5, 8, 2, 3, 2, 7, 8],
       [4, 4, 2, 7, 7, 3, 5],
       [2, 6, 5, 5, 7, 5, 4],
       [8, 6, 4, 6, 3, 2, 3]], dtype=int32)

In [41]:
arr2[::3]

array([[6, 6, 6, 5, 5, 2, 5],
       [2, 6, 5, 5, 7, 5, 4]], dtype=int32)

In [42]:
arr2

array([[6, 6, 6, 5, 5, 2, 5],
       [5, 8, 2, 3, 2, 7, 8],
       [4, 4, 2, 7, 7, 3, 5],
       [2, 6, 5, 5, 7, 5, 4],
       [8, 6, 4, 6, 3, 2, 3]], dtype=int32)

In [43]:
arr2[3,4] 

np.int32(7)

In [44]:
print(arr2[3,4])

7


In [45]:
arr2

array([[6, 6, 6, 5, 5, 2, 5],
       [5, 8, 2, 3, 2, 7, 8],
       [4, 4, 2, 7, 7, 3, 5],
       [2, 6, 5, 5, 7, 5, 4],
       [8, 6, 4, 6, 3, 2, 3]], dtype=int32)

In [46]:
print(arr2[-4, -5]) 

2


In [47]:
arr2[0, 1] = 10

In [48]:
arr2

array([[ 6, 10,  6,  5,  5,  2,  5],
       [ 5,  8,  2,  3,  2,  7,  8],
       [ 4,  4,  2,  7,  7,  3,  5],
       [ 2,  6,  5,  5,  7,  5,  4],
       [ 8,  6,  4,  6,  3,  2,  3]], dtype=int32)

In [49]:
arr2[:, 0]

array([6, 5, 4, 2, 8], dtype=int32)

In [50]:
arr2[:, -3]

array([5, 2, 7, 7, 3], dtype=int32)

In [51]:
arr2

array([[ 6, 10,  6,  5,  5,  2,  5],
       [ 5,  8,  2,  3,  2,  7,  8],
       [ 4,  4,  2,  7,  7,  3,  5],
       [ 2,  6,  5,  5,  7,  5,  4],
       [ 8,  6,  4,  6,  3,  2,  3]], dtype=int32)

In [52]:
arr2[2:5, 2:5] 

array([[2, 7, 7],
       [5, 5, 7],
       [4, 6, 3]], dtype=int32)

In [53]:
arr2

array([[ 6, 10,  6,  5,  5,  2,  5],
       [ 5,  8,  2,  3,  2,  7,  8],
       [ 4,  4,  2,  7,  7,  3,  5],
       [ 2,  6,  5,  5,  7,  5,  4],
       [ 8,  6,  4,  6,  3,  2,  3]], dtype=int32)

In [54]:
arr2[1:4, 2:4]

array([[2, 3],
       [2, 7],
       [5, 5]], dtype=int32)

masking or filter in numpy 

In [55]:
arr2

array([[ 6, 10,  6,  5,  5,  2,  5],
       [ 5,  8,  2,  3,  2,  7,  8],
       [ 4,  4,  2,  7,  7,  3,  5],
       [ 2,  6,  5,  5,  7,  5,  4],
       [ 8,  6,  4,  6,  3,  2,  3]], dtype=int32)

In [56]:
arr2 > 5 

array([[ True,  True,  True, False, False, False, False],
       [False,  True, False, False, False,  True,  True],
       [False, False, False,  True,  True, False, False],
       [False,  True, False, False,  True, False, False],
       [ True,  True, False,  True, False, False, False]])

In [57]:
arr2[arr2 > 5] 

array([ 6, 10,  6,  8,  7,  8,  7,  7,  6,  7,  8,  6,  6], dtype=int32)

In [58]:
arr2[arr2 >= 5] 

array([ 6, 10,  6,  5,  5,  5,  5,  8,  7,  8,  7,  7,  5,  6,  5,  5,  7,
        5,  8,  6,  6], dtype=int32)

In [59]:
arr2[arr2 != 5]

array([ 6, 10,  6,  2,  8,  2,  3,  2,  7,  8,  4,  4,  2,  7,  7,  3,  2,
        6,  7,  4,  8,  6,  4,  6,  3,  2,  3], dtype=int32)

In [60]:
arr2[arr2 == 5]

array([5, 5, 5, 5, 5, 5, 5, 5], dtype=int32)

In [ ]:
Without work on #import * can you plase find the median,mode

In [75]:
import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5])
print(arr)

[0 1 2 3 4 5]


In [76]:
arr

array([0, 1, 2, 3, 4, 5])

In [99]:
arr.reshape(3,2)  

array([[0, 1],
       [2, 3],
       [4, 5]])

In [100]:
arr.reshape(6,1) 

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [101]:
arr.reshape(2,4) 

ValueError: cannot reshape array of size 6 into shape (2,4)

In [102]:
arr.reshape(3,2,order='C') 

array([[0, 1],
       [2, 3],
       [4, 5]])

In [103]:
arr.reshape(2,3,order='C') 

array([[0, 1, 2],
       [3, 4, 5]])

In [104]:
arr.reshape(2,3,order='F')

array([[0, 2, 4],
       [1, 3, 5]])

In [77]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [78]:
arr.reshape(4,3)

ValueError: cannot reshape array of size 6 into shape (4,3)

In [79]:
arr.reshape(3, 2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [105]:
# importing Numpy package 
import numpy as np

# creating a Numpy array
num_array = np.arange(100).reshape(20, 5)
print(num_array)

# Display array in Fortran order 

print("\n  C type array:")
for num_array in np.nditer(num_array, order="C"):
	print(num_array,end=' ')

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]
 [50 51 52 53 54]
 [55 56 57 58 59]
 [60 61 62 63 64]
 [65 66 67 68 69]
 [70 71 72 73 74]
 [75 76 77 78 79]
 [80 81 82 83 84]
 [85 86 87 88 89]
 [90 91 92 93 94]
 [95 96 97 98 99]]

  C type array:
0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 

In [109]:
mat = np.arange(0,100).reshape(10,10) 

In [110]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [111]:
mat = np.arange(0,100).reshape(10,10) 

In [112]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

row = 4
col = 5

In [80]:
arr

array([0, 1, 2, 3, 4, 5])

In [81]:
arr.max()

np.int64(5)

In [82]:
arr.min()

np.int64(0)

In [84]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [85]:
np.zeros(5, dtype=int)

array([0, 0, 0, 0, 0])

In [86]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [87]:
np.zeros((10,10),dtype = int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])