In [1]:
import numpy as np

#creat a array from list 

In [2]:
a = np.array([1,2,3])
print("Array a:",a)

Array a: [1 2 3]


In [3]:
b = np.arange(0,10,3)
print("Array b:",b)

Array b: [0 3 6 9]


In [4]:
d = np.zeros((2,3))
print("Array d: \n",d)

Array d: 
 [[0. 0. 0.]
 [0. 0. 0.]]


In [5]:
d = np.zeros((2,3),dtype=int)
print("Array d: \n",d)

Array d: 
 [[0 0 0]
 [0 0 0]]


In [6]:
e = np.ones((3,2))
print("Array d: \n",e)

Array d: 
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [7]:
f = np.eye(4)
print("Identify matrix f: \n",f)

Identify matrix f: 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [8]:
###Array manupulation function

In [9]:
#reshape an array
a1 = np.array([1,2,3])
reshaped = np.reshape(a1,(1,3))
print("Reshaped array:",reshaped)

Reshaped array: [[1 2 3]]


In [10]:
#reshape an array
a1 = np.array([1,2,3])
reshaped = np.reshape(a1,(3,1))
print("Reshaped array:",reshaped)

Reshaped array: [[1]
 [2]
 [3]]


In [11]:
#Flatten an array
f1 = np.array([[1,2],[3,4],[5,6],[7,8],[9,10]])
flattened = np.ravel(f1)
print("flattened array:",flattened)

flattened array: [ 1  2  3  4  5  6  7  8  9 10]


In [12]:
#Transpose an array
e1 = np.array([[1,2],[3,4]])
Transposed = np.transpose(e1)
print("Transposed array:",Transposed)

Transposed array: [[1 3]
 [2 4]]


In [13]:
#Stacked horizantal array
a2 = np.array([1,2])
b2 = np.array([3,4])
stacked = np.hstack([a2,b2])
print("Stacked array:",stacked)

Stacked array: [1 2 3 4]


In [14]:
#Stacked horizantal array
a2 = np.array([1,2])
b2 = np.array([3,4])
stacked = np.vstack([a2,b2])
print("Stacked array:",stacked)

Stacked array: [[1 2]
 [3 4]]


MATHEMATICAL FUNCTIONS

In [19]:
e1 = np.array([1,2,3,4])
added = np.add(e1,2)
print("Added e1:",added)

Added e1: [3 4 5 6]


In [20]:
e2 = np.array([1,2,3,4])
squared = np.power(e1,2)
print("Squred e2:",squared)

Squred e2: [ 1  4  9 16]


In [22]:
# Square root of each element
sqrt_val = np.sqrt(e1)  # Square root of each element
print("Square root of e1:", sqrt_val)

Square root of e1: [1.         1.41421356 1.73205081 2.        ]


In [23]:
print(e1)
print(e2)

[1 2 3 4]
[1 2 3 4]


In [24]:
a3 = np.array([1,2,3,4])# dimention are not same then it gives the error in dot product
dot_product = np.dot(e1,e2)
print("Dot product of e1 and e2:",dot_product)

Dot product of e1 and e2: 30


STASTICAL FUNCTION 

In [25]:
s = np.array([1,2,3,4])
mean = np.mean(s)
print("Mean of s:",mean)

Mean of s: 2.5


In [26]:
#standad deviation of array
var = np.var(s)
print("Variance of s :", var)

Variance of s : 1.25


In [27]:
#standad deviation of array
std_dev = np.std(s)
print("Standad deviation of s :", std_dev)

Standad deviation of s : 1.118033988749895


In [29]:
minimum = np.min(s)
print("Min of s:", minimum)

Min of s: 1


In [30]:
#min & max 
minimum = np.min(s)
print("Min of s:", minimum)

Min of s: 1


LINEAR ALGEBRA FUNCTION

In [31]:
# Create a matrix
matrix = np.array([[1, 2], [3, 4]]) 
matrix

array([[1, 2],
       [3, 4]])

RANDOM SAMPLING FUNCTIONS

In [32]:
random_vals = np.random.rand(3)
print("Random values:",random_vals)

Random values: [0.25593579 0.91812608 0.76091542]


In [33]:
random_ints = np.random.randint(0,10,size=4)
print("Random integers:",random_ints)

Random integers: [1 6 9 5]


In [29]:
np.random.seed(0)
random_ints = np.random.randint(0,10,size=5)
print("Random integers:",random_ints)

Random integers: [5 0 3 3 7]


BOOLEAN & LOGICAL FUNCTIONS

In [39]:
# Check if all elements are True

# all
logical_test = np.array([True, False, True]) 
all_true = np.all(logical_test)  # Check if all are True
print("All elements True:", all_true)

All elements True: False


In [40]:
# Check if all elements are True
logical_test = np.array([True, False, True])
all_true = np.all(logical_test)  # Check if all are True
print("All elements True:", all_true)

All elements True: False


In [41]:
# Check if all elements are True
logical_test = np.array([False, False, False])
all_true = np.all(logical_test)  # Check if all are True
print("All elements True:", all_true)

All elements True: False


In [42]:
# Check if any elements are True
# any
any_true = np.any(logical_test)  # Check if any are True
print("Any elements True:", any_true)

Any elements True: False


SET OPERATIONS

In [45]:
# Intersection of two arrays
set_a = np.array([1, 2, 3, 4])
set_b = np.array([3, 4, 5, 6])
intersection = np.intersect1d(set_a, set_b)
print("Intersection of a and b:", intersection)

Intersection of a and b: [3 4]


In [46]:
# Union of two arrays
union = np.union1d(set_a, set_b)
print("Union of a and b:", union)

Union of a and b: [1 2 3 4 5 6]


ARRAY ATRIBUTE FUNCTION

In [47]:
# Array attributes
a = np.array([1, 2, 3])
shape = a.shape  # Shape of the array
size = a.size    # Number of elements
dimensions = a.ndim  # Number of dimensions
dtype = a.dtype   # Data type of the array

print("Shape of a:", shape)
print("Size of a:", size)
print("Number of dimensions of a:", dimensions)
print("Data type of a:", dtype)


Shape of a: (3,)
Size of a: 3
Number of dimensions of a: 1
Data type of a: int64


OTHER FUNCTION

In [48]:
# Create a copy of an array
a = np.array([1, 2, 3])
copied_array = np.copy(a)  # Create a copy of array a
print("Copied array:", copied_array)

Copied array: [1 2 3]


In [49]:
# Size in bytes of an array
array_size_in_bytes = a.nbytes  # Size in bytes
print("Size of a in bytes:", array_size_in_bytes)

Size of a in bytes: 24


In [50]:
# Check if two arrays share memory
shared = np.shares_memory(a, copied_array)  # Check if arrays share memory
print("Do a and copied_array share memory?", shared)

Do a and copied_array share memory? False
